In [3]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [4]:
arr_2d=np.array([[1,2],[3,4],[7,8]])
print(arr_2d)

[[1 2]
 [3 4]
 [7 8]]


In [3]:
arr_zeros=np.zeros((3,4))
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
arr_arrage=np.arange(0,19,2)
print(arr_arrage)

[ 0  2  4  6  8 10 12 14 16 18]


In [8]:
arr_linspace=np.linspace(0,1,10)
print(arr_linspace)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
